version: 1.0.{build}
#image: Visual Studio 2013
image: Visual Studio 2022
configuration: Release
init:
  - set PATH=C:\Program Files\Java\jdk15\bin;%PATH%
  - set JAVA_HOME_11_X64=C:\Program Files\Java\jdk15
  - set JAVA_HOME=C:\Program Files\Java\jdk15
environment:
  github_token: 'secure: TaDEavUfTj6EgwcO7y5njQVS5Z9bBU/fVFuSApo5XEO6FSBT5UzJQmyJjbhIFDZb'
  myget_token: 'secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF'
install:
- choco install gitversion.portable -y
- cmd: nuget sources add -Name EPiServerFeed -Source http://nuget.episerver.com/feed/packages.svc/
- cmd: nuget sources add -Name EPiServerBetaFeed -Source https://www.myget.org/F/cmscore/api/v2
before_build:
- cmd: nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build_script:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet sonarscanner begin /k:"jstemerdink:EPi.Libraries.Logging.Serilog" /n:"EPi.Libraries.Logging.Serilog" /d:"sonar.host.url=https://sonarcloud.io" /o:"jstemerdink-github" /d:"sonar.login=0b0eec6902ab7d776899f79bfeff15d313dd6e09"
  - msbuild "EPi.Libraries.Logging.Serilog.sln"
  - dotnet sonarscanner end /d:"sonar.login=0b0eec6902ab7d776899f79bfeff15d313dd6e09"
after_build:
#- cmd: nuget pack EPi.Libraries.Logging.Serilog\EPi.Libraries.Logging.Serilog.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.%GitVersion_NuGetVersion%.nupkg"
#- cmd: nuget pack EPi.Libraries.Logging.Serilog.AppSettings\EPi.Libraries.Logging.Serilog.AppSettings.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.AppSettings.%GitVersion_NuGetVersion%.nupkg"
#- 7z a EPi.Libraries.Logging.Serilog.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog\bin\Release\EPi.Libraries.Logging.Serilog.dll
#- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.%GitVersion_NuGetVersion%.zip"
#- 7z a EPi.Libraries.Logging.Serilog.AppSettings.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog.AppSettings\bin\Release\EPi.Libraries.Logging.Serilog.AppSettings.dll
#- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.AppSettings.%GitVersion_NuGetVersion%.zip"
before_package:
- ps: >-
    Write-Host -NoNewline "Installing NuGet 3.3.0..."

    if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
#deploy:
#- provider: NuGet
#  server: https://www.myget.org/F/epi-libraries/api/v2/package
#  api_key:
#    secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF
#  skip_symbols: true
#  artifact: /.*\.nupkg/
#  on:
#    branch: develop             # release from develop branch only
#    #appveyor_repo_tag: true     # deploy on tag push only
#- provider: GitHub
#  auth_token:
#    secure: TaDEavUfTj6EgwcO7y5njQVS5Z9bBU/fVFuSApo5XEO6FSBT5UzJQmyJjbhIFDZb
#  artifact: /.*\.zip/
#  on:
#    branch: master              # release from master branch only
    #appveyor_repo_tag: true     # deploy on tag push only
